Repository kakao-tech-campus-2nd-step3/Team7_BE, pull requests merged in 2024-11, with the labels that each got.

#92 데이터로더에 있는 Insert문을 SQL문으로 변경해요
  src/main/java/team7/inplace/influencer/config/InfluencerDataLoader.java
  src/main/java/team7/inplace/place/config/DataLoader.java
  src/main/resources/application-db.yaml
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
Labels: 🔨 Refactor

#94 500에러를 확인할 수 있는 관리자 페이지를 만들었어요
  src/main/java/team7/inplace/admin/AdminPageController.java
  src/main/java/team7/inplace/admin/ErrorLogController.java
  src/main/java/team7/inplace/admin/adminPageController.java
  src/main/java/team7/inplace/global/exception/ErrorLog.java
  src/main/java/team7/inplace/global/exception/ErrorLogRepository.java
  src/main/java/team7/inplace/global/exception/InplaceExceptionHandler.java
  src/main/resources/sql/schema.sql
  src/main/resources/static/css/error_logs_style.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/js/error-logs.js
  src/main/resources/templates/admin/error-logs.html
  src/main/resources/templates/admin/video.html
Labels: ✨ Feature

#93 [Feat] #75 장소에 대한 리뷰를 추가하고 조회해요
  src/main/java/team7/inplace/global/exception/code/ReviewErrorCode.java
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/place/presentation/PlaceController.java
  src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
  src/main/java/team7/inplace/place/presentation/dto/ReviewRequest.java
  src/main/java/team7/inplace/place/presentation/dto/ReviewResponse.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/main/java/team7/inplace/review/application/dto/ReviewCommand.java
  src/main/java/team7/inplace/review/application/dto/ReviewInfo.java
  src/main/java/team7/inplace/review/domain/Review.java
  src/main/java/team7/inplace/review/persistence/ReviewRepository.java
  src/test/java/team7/inplace/review/ReviewServiceTest.java
Labels: ✨ Feature

#98 [ Master] 9주차 PR
  .gitmodules
  src/main/java/team7/inplace/admin/AdminPageController.java
  src/main/java/team7/inplace/admin/ErrorLogController.java
  src/main/java/team7/inplace/admin/adminPageController.java
  src/main/java/team7/inplace/crawling/application/CrawlingFacade.java
  src/main/java/team7/inplace/crawling/application/VideoCrawlingService.java
  src/main/java/team7/inplace/crawling/application/dto/CrawlingVideoViewInfo.java
  src/main/java/team7/inplace/crawling/client/YoutubeClient.java
  src/main/java/team7/inplace/global/exception/ErrorLog.java
  src/main/java/team7/inplace/global/exception/ErrorLogRepository.java
  src/main/java/team7/inplace/global/exception/InplaceExceptionHandler.java
  src/main/java/team7/inplace/global/exception/code/ReviewErrorCode.java
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/influencer/config/InfluencerDataLoader.java
  src/main/java/team7/inplace/place/application/PlaceService.java
  src/main/java/team7/inplace/place/application/command/PlacesCommand.java
  src/main/java/team7/inplace/place/config/DataLoader.java
  src/main/java/team7/inplace/place/presentation/PlaceController.java
  src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
  src/main/java/team7/inplace/place/presentation/dto/ReviewRequest.java
  src/main/java/team7/inplace/place/presentation/dto/ReviewResponse.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/main/java/team7/inplace/review/application/dto/ReviewCommand.java
  src/main/java/team7/inplace/review/application/dto/ReviewInfo.java
  src/main/java/team7/inplace/review/domain/Review.java
  src/main/java/team7/inplace/review/persistence/ReviewRepository.java
  src/main/java/team7/inplace/video/application/VideoFacade.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/application/command/VideoCommand.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/resources/application-db.yaml
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
  src/main/resources/static/css/error_logs_style.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/js/error-logs.js
  src/main/resources/templates/admin/error-logs.html
  src/main/resources/templates/admin/video.html
  src/test/java/team7/inplace/place/application/PlaceServiceTest.java
  src/test/java/team7/inplace/place/persistence/PlaceRepositoryTest.java
  src/test/java/team7/inplace/review/ReviewServiceTest.java
  src/test/java/team7/inplace/video/domain/VideoTest.java
Labels: 💻 리뷰 요청

#100 [Feat] #99 비디오 어드민 페이지 고도화를 진행했어요
  src/main/java/team7/inplace/admin/AdminPageController.java
  src/main/resources/static/css/error_logs_style.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/video.js
  src/main/resources/templates/admin/error-logs.html
  src/main/resources/templates/admin/video.html
Labels: ✨ Feature

#102 [feat] #50-frontend 주소로 redirect
  build.gradle
  src/main/generated/team7/inplace/favoriteInfluencer/domain/QFavoriteInfluencer.java
  src/main/generated/team7/inplace/global/exception/QErrorLog.java
  src/main/generated/team7/inplace/oauthToken/domain/QOauthToken.java
  src/main/generated/team7/inplace/place/domain/QPlace.java
  src/main/generated/team7/inplace/review/domain/QReview.java
  src/main/generated/team7/inplace/video/domain/QVideo.java
  src/main/java/team7/inplace/global/exception/code/UserErrorCode.java
  src/main/java/team7/inplace/global/kakao/config/KakaoApiProperties.java
  src/main/java/team7/inplace/global/rest/WebClientConfig.java
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/oauthToken/application/OauthTokenService.java
  src/main/java/team7/inplace/oauthToken/application/command/OauthTokenCommand.java
  src/main/java/team7/inplace/oauthToken/domain/OauthToken.java
  src/main/java/team7/inplace/oauthToken/persistence/OauthTokenRepository.java
  src/main/java/team7/inplace/placeMessage/util/Button.java
  src/main/java/team7/inplace/placeMessage/util/Content.java
  src/main/java/team7/inplace/placeMessage/util/KakaoMessageClient.java
  src/main/java/team7/inplace/placeMessage/util/KakaoMessageMaker.java
  src/main/java/team7/inplace/placeMessage/util/Link.java
  src/main/java/team7/inplace/placeMessage/util/LocationTemplate.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/main/java/team7/inplace/security/application/CustomOAuth2UserService.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/config/SecurityServiceConfig.java
  src/main/java/team7/inplace/security/config/SecurityUtilConfig.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
  src/main/java/team7/inplace/security/filter/TokenType.java
  src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/security/util/AuthorizationUtil.java
  src/main/java/team7/inplace/security/util/CookieUtil.java
  src/main/java/team7/inplace/security/util/TokenEncryptionUtil.java
  src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
  src/main/java/team7/inplace/user/application/UserService.java
  src/main/resources/application-kakao.yaml
  src/main/resources/application-security.yaml
Labels: ✨ Feature

#107 Admin페이지에서 장소 정보를 등록할 수 있는 기능을 추가했어요
  src/main/java/team7/inplace/admin/AdminPageController.java
  src/main/java/team7/inplace/crawling/application/CrawlingFacade.java
  src/main/java/team7/inplace/crawling/application/KakaoCrawlingService.java
  src/main/java/team7/inplace/crawling/application/VideoCrawlingService.java
  src/main/java/team7/inplace/crawling/application/YoutubeCrawlingService.java
  src/main/java/team7/inplace/crawling/application/dto/CrawlingInfo.java
  src/main/java/team7/inplace/crawling/application/dto/CrawlingVideoViewInfo.java
  src/main/java/team7/inplace/crawling/client/KakaoMapClient.java
  src/main/java/team7/inplace/crawling/presentation/CrawlingController.java
  src/main/java/team7/inplace/global/exception/code/PlaceErrorCode.java
  src/main/java/team7/inplace/place/application/PlaceService.java
  src/main/java/team7/inplace/place/application/command/PlacesCommand.java
  src/main/java/team7/inplace/video/application/VideoFacade.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/resources/static/js/video.js
  src/main/resources/templates/admin/video.html
  src/test/java/team7/inplace/crawling/client/KakaoMapClientTest.java
Labels: ✨ Feature

#110 [Feat, Test, Refactor] 조회수 기반 동영상 정렬 및 조회 기능을 만들었어요
  build.gradle
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
  src/main/java/team7/inplace/video/presentation/dto/VideoSearchParams.java
  src/test/java/team7/inplace/util/TestUtil.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor, ✅ Test

#109 [Feat] #50 장소정보를 보내는 기능을 작성했어요!
  src/main/generated/team7/inplace/LikedPlace/domain/QLikedPlace.java
  src/main/java/team7/inplace/global/scheduler/ScheduledExecutorConfig.java
  src/main/java/team7/inplace/place/application/PlaceService.java
  src/main/java/team7/inplace/place/domain/Address.java
  src/main/java/team7/inplace/placeMessage/application/KakaoMessageService.java
  src/main/java/team7/inplace/placeMessage/application/PlaceMessageFacade.java
  src/main/java/team7/inplace/placeMessage/application/command/PlaceMessageCommand.java
  src/main/java/team7/inplace/placeMessage/presentation/PlaceMessageController.java
  src/main/java/team7/inplace/placeMessage/presentation/PlaceMessageControllerApiSpec.java
  src/main/java/team7/inplace/placeMessage/util/Button.java
  src/main/java/team7/inplace/placeMessage/util/Content.java
  src/main/java/team7/inplace/placeMessage/util/FeedTemplate.java
  src/main/java/team7/inplace/placeMessage/util/KakaoMessageClient.java
  src/main/java/team7/inplace/placeMessage/util/KakaoMessageMaker.java
  src/main/java/team7/inplace/placeMessage/util/Link.java
  src/main/java/team7/inplace/placeMessage/util/LocationTemplate.java
  src/main/resources/application-security.yaml
Labels: ✨ Feature

#119 [chore] #50 console에 log 남는 거 삭제
  src/main/java/team7/inplace/placeMessage/util/KakaoMessageMaker.java
Labels: ✨ Feature

#127 [Feat] 비디오 삭제기능 및 Admin페이지 수정
  src/main/java/team7/inplace/crawling/application/CrawlingFacade.java
  src/main/java/team7/inplace/crawling/application/YoutubeCrawlingService.java
  src/main/java/team7/inplace/crawling/application/dto/CrawlingInfo.java
  src/main/java/team7/inplace/crawling/persistence/YoutubeChannelRepository.java
  src/main/java/team7/inplace/video/application/VideoFacade.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
  src/main/resources/sql/schema.sql
  src/main/resources/static/js/video.js
  src/main/resources/templates/admin/video.html
Labels: ✨ Feature

#131 [Feat] #130 인플루언서 관련 리팩터링했어요
  src/main/java/team7/inplace/favoriteInfluencer/application/FavoriteInfluencerService.java
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/influencer/application/dto/InfluencerNameInfo.java
  src/main/java/team7/inplace/influencer/persistence/InfluencerRepository.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerController.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerControllerApiSpec.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerListResponse.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerNameResponse.java
  src/main/java/team7/inplace/place/presentation/dto/ReviewRequest.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/test/java/team7/inplace/influencer/InfluencerControllerTest.java
  src/test/java/team7/inplace/influencer/InfluencerServiceTest.java
Labels: 📬 API, 🔨 Refactor

#138 [Test] 비디오 도메인에 fetch join을 적용하고 부하 테스트를 진행해요
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#136 [Fix] #50 - Token이 Expire되어도 permitAll이면 허용
  src/main/java/team7/inplace/global/exception/code/AuthorizationErrorCode.java
  src/main/java/team7/inplace/global/rest/WebClientConfig.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
  src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/security/util/CookieUtil.java
  src/main/java/team7/inplace/security/util/JwtUtil.java
  src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
  src/test/java/team7/inplace/security/util/JwtUtilTest.java
Labels: 🐞 BugFix

#140 [Docs] README 파일 초안 작성
  README.md
Labels: 📃 Docs

#151 [refactor] #149 PlacesResponse 형식 변환
  src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
Labels: 🔨 Refactor

#150 [Refactor] 잘못 설정된 인증 부분을 삭제해요
  src/main/java/team7/inplace/video/application/VideoService.java
Labels: 🔨 Refactor

#155 [Fix] RefreshToken
  src/main/generated/team7/inplace/likedPlace/domain/QLikedPlace.java
  src/main/java/team7/inplace/global/exception/code/AuthorizationErrorCode.java
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
  src/main/java/team7/inplace/token/application/RefreshTokenFacade.java
  src/main/java/team7/inplace/token/application/dto/TokenCommand.java
  src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
  src/test/java/team7/inplace/security/config/SecurityConfigTest.java
Labels: 🐞 BugFix

#156 [Fix] 유저 닉네임 변경 api 명세 오류를 수정해요
  src/main/java/team7/inplace/user/presentation/UserControllerApiSepc.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: 🐞 BugFix

#143 [Feat] #142 마이페이지에 필요한 정보를 반환해요
  src/main/java/team7/inplace/favoriteInfluencer/application/FavoriteInfluencerService.java
  src/main/java/team7/inplace/favoriteInfluencer/persistent/FavoriteInfluencerRepository.java
  src/main/java/team7/inplace/likedPlace/persistence/LikedPlaceRepository.java
  src/main/java/team7/inplace/place/application/PlaceService.java
  src/main/java/team7/inplace/place/application/dto/LikedPlaceInfo.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/main/java/team7/inplace/review/application/dto/MyReviewInfo.java
  src/main/java/team7/inplace/review/persistence/ReviewRepository.java
  src/main/java/team7/inplace/review/presentation/ReviewController.java
  src/main/java/team7/inplace/review/presentation/ReviewControllerApiSpec.java
  src/main/java/team7/inplace/security/application/CurrentUserProvider.java
  src/main/java/team7/inplace/user/application/UserFacade.java
  src/main/java/team7/inplace/user/application/UserService.java
  src/main/java/team7/inplace/user/application/dto/UserInfo.java
  src/main/java/team7/inplace/user/presentation/UserController.java
  src/main/java/team7/inplace/user/presentation/UserControllerApiSepc.java
  src/main/java/team7/inplace/user/presentation/dto/LikedInfluencerResponse.java
  src/main/java/team7/inplace/user/presentation/dto/LikedPlaceResponse.java
  src/main/java/team7/inplace/user/presentation/dto/MyReviewResponse.java
  src/main/java/team7/inplace/user/presentation/dto/UserInfoResponse.java
  src/test/java/team7/inplace/review/ReviewServiceTest.java
Labels: ✨ Feature

#160 검색어 자동 완성 기능을 추가했어요~!
  src/main/java/team7/inplace/search/application/SearchService.java
  src/main/java/team7/inplace/search/application/dto/AutoCompletionInfo.java
  src/main/java/team7/inplace/search/application/dto/SearchType.java
  src/main/java/team7/inplace/search/config/MatchAgainstFunctionContributor.java
  src/main/java/team7/inplace/search/persistence/InfluencerSearchRepository.java
  src/main/java/team7/inplace/search/persistence/PlaceSearchRepository.java
  src/main/java/team7/inplace/search/persistence/SearchRepository.java
  src/main/java/team7/inplace/search/persistence/VideoSearchRepository.java
  src/main/java/team7/inplace/search/persistence/dto/SearchResult.java
  src/main/java/team7/inplace/search/presentation/SearchController.java
  src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
  src/main/java/team7/inplace/video/application/dto/VideoInfo.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: ✨ Feature

#165 [feat] cookie samesite 속성을 none으로 설정
  src/main/java/team7/inplace/security/util/CookieUtil.java
Labels: ✨ Feature

#161 [Docs] 리포지토리 정보 추가
  README.md
Labels: 📃 Docs

#168 [fix] credential request를 기반한 cors 설정
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#166 [Feat] 장소 조회 API를 추가했어요
  src/main/java/team7/inplace/likedPlace/persistence/LikedPlaceRepository.java
  src/main/java/team7/inplace/search/application/SearchService.java
  src/main/java/team7/inplace/search/application/dto/PlaceSearchInfo.java
  src/main/java/team7/inplace/search/presentation/SearchController.java
  src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
  src/main/resources/sql/schema.sql
Labels: ✨ Feature

#169 [Fix] cors 설정1
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#170 [fix] cors 설정2
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#175 [Chore] 로그 남기기
  src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
  src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
Labels: ✨ Feature

#176 [chore] log
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
Labels: ✨ Feature

#178 [chore] log2
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
Labels: 🐞 BugFix

#179 [chore] log 3
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
Labels: 🐞 BugFix

#177 [Refactor] 마이페이지 조회에 fetch join 적용했어요
  src/main/java/team7/inplace/likedPlace/persistence/LikedPlaceRepository.java
  src/main/java/team7/inplace/place/application/PlaceService.java
  src/main/java/team7/inplace/review/application/ReviewService.java
  src/main/java/team7/inplace/review/persistence/ReviewRepository.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
Labels: 🔨 Refactor

#182 [Chore] log 삭제 및 placeMessage 테스트 위한 장소정보 보내기 1분 설정
  src/main/java/team7/inplace/placeMessage/application/PlaceMessageFacade.java
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
  src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
Labels: ✨ Feature

#181 [Feat] 배너를 업로드하고 반환하는 기능을 추가했어요.
  build.gradle
  src/main/java/team7/inplace/admin/AdminPageController.java
  src/main/java/team7/inplace/admin/application/BannerService.java
  src/main/java/team7/inplace/admin/application/command/BannerCommand.java
  src/main/java/team7/inplace/admin/application/dto/BannerInfo.java
  src/main/java/team7/inplace/admin/domain/Banner.java
  src/main/java/team7/inplace/admin/persistence/BannerRepository.java
  src/main/java/team7/inplace/admin/persistence/BannerS3Repository.java
  src/main/java/team7/inplace/admin/presentation/BannerController.java
  src/main/java/team7/inplace/admin/presentation/BannerRequest.java
  src/main/java/team7/inplace/admin/presentation/BannerResponse.java
  src/main/java/team7/inplace/infra/s3/AwsProperties.java
  src/main/java/team7/inplace/infra/s3/S3Config.java
  src/main/resources/application-s3.yaml
  src/main/resources/application.yaml
  src/main/resources/sql/schema.sql
  src/main/resources/static/css/banner.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/js/banner.js
  src/main/resources/templates/admin/banner.html
Labels: ✨ Feature

#174 [Docs] Readme 파일 내용 수정
  README.md
Labels: 📃 Docs

#184 [Docs] 리드미 수정 수정
  README.md
Labels: 📃 Docs

#189 [Fix] 에러나는 테스트코드를 수정했어요
  src/main/java/team7/inplace/video/domain/Video.java
  src/test/java/team7/inplace/crawling/application/AddressUtilTest.java
  src/test/java/team7/inplace/crawling/client/YoutubeClientTest.java
Labels: 🐞 BugFix

#186 [Refactor] 마이페이지 리뷰 조회 시 placeName 추가했어요
  src/main/java/team7/inplace/review/application/dto/MyReviewInfo.java
Labels: 📬 API

#192 [Refactor] 마이페이지 인플루언서 반환 값 수정했어요
  src/main/java/team7/inplace/user/presentation/dto/LikedInfluencerResponse.java
Labels: 🔨 Refactor

#194 [Fix] #193 비디오 도메인의 오류를 수정했어요
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
Labels: 🐞 BugFix

#196 [Docs] 한글로 독스를 업데이트합니다.
  README.md
Labels: 📃 Docs

#197 [Docs] 기능 흐름 추가 및 테스트 항목 추가
  README.md
Labels: 📃 Docs

#199 [fix] api path 수정
  src/main/java/team7/inplace/admin/banner/presentation/BannerController.java
  src/main/resources/static/js/banner.js
Labels: 🐞 BugFix

#200 [Fix] API를 수정합니다
  src/main/java/team7/inplace/admin/banner/presentation/BannerResponse.java
  src/main/resources/templates/admin/banner.html
Labels: 🐞 BugFix

#206 [ Feat] Influencer 검색기능(Pagination) 추가
  src/main/java/team7/inplace/search/application/SearchService.java
  src/main/java/team7/inplace/search/persistence/InfluencerSearchRepository.java
  src/main/java/team7/inplace/search/presentation/SearchController.java
  src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
Labels: ✨ Feature

#205 [Docs] #185 readme 파일 수정 수정 수정
  README.md
Labels: 📃 Docs

#213 [docs] readme 내용 추가
  README.md
Labels: 📃 Docs

#217 [Feat] cloudfront 주소로 변경
  src/main/java/team7/inplace/admin/banner/persistence/BannerS3Repository.java
  src/main/java/team7/inplace/place/application/dto/PlaceDetailInfo.java
Labels: ✨ Feature

#221 [docs] readme 순서 작성
  README.md
Labels: 📃 Docs

#223 [fix] 반환값 변경
  src/main/java/team7/inplace/place/application/dto/PlaceDetailInfo.java
Labels: 🐞 BugFix

#225 Docs/#185 readme
  README.md
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
Labels: 🐞 BugFix

#224 [Docs] readme 파일 수정
  README.md
Labels: 📃 Docs

#226 [fix] nickname 변경할때 바디로 받음
  src/main/java/team7/inplace/user/presentation/UserController.java
Labels: 🐞 BugFix

#227 [fix] authentication 실패 시 401 반환
  src/main/java/team7/inplace/security/config/SecurityEntryPointConfig.java
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
Labels: 🐞 BugFix

#228 [Docs] Readme 파일 내용 수정
  README.md
Labels: 📃 Docs

#232 [Docs] Read 추가
  README.md
  src/test/java/team7/inplace/security/config/SecurityConfigTest.java
Labels: 📃 Docs

#235 [Fix] 비디오 테스트 문제 해결해요
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: 🐞 BugFix, ✅ Test

#236 [Feat] #231 mypage 반환 테스트해요
  README.md
  src/test/java/team7/inplace/favoriteInfluencer/FavoriteInfluencerServiceTest.java
  src/test/java/team7/inplace/place/application/PlaceServiceTest.java
  src/test/java/team7/inplace/review/ReviewServiceTest.java
Labels: ✅ Test

#237 [test] videorepositorytest 깨지는 거 해결
  src/main/generated/team7/inplace/admin/banner/domain/QBanner.java
  src/main/generated/team7/inplace/admin/crawling/domain/QYoutubeChannel.java
  src/main/generated/team7/inplace/admin/error/QErrorLog.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/test/java/team7/inplace/config/annotation/CustomRepositoryTest.java
Labels: ✅ Test

#239 [chore] 최종 검사용 admin permitAll()
  src/main/java/team7/inplace/security/config/SecurityConfig.java
Labels: 💻 리뷰 요청

#241 [Feat] 스케쥴링 적용
  README.md
  prod.env
  src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
  src/main/java/team7/inplace/global/scheduler/ScheduledExecutorConfig.java
Labels: ✨ Feature

#242 [fix] nickname 변경 pathvariable 사용
  src/main/java/team7/inplace/user/presentation/UserController.java
Labels: 🐞 BugFix
