Repository kakao-tech-campus-2nd-step3/Team7_BE, pull requests merged in 2024-09, with the labels that each got.

#11 [기능] Feat/#7 place Category 목록 조회 기능을 구현했어요
  README.md
  src/main/java/team7/inplace/place/controller/PlaceController.java
  src/main/java/team7/inplace/place/domain/Category.java
  src/main/java/team7/inplace/place/domain/CategoryListDTO.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/place/repository/PlaceRepository.java
  src/main/java/team7/inplace/place/service/PlaceService.java
  src/main/java/team7/inplace/place/service/PlaceServiceImpl.java
  src/test/java/team7/inplace/place/controller/PlaceControllerTest.java
  src/test/java/team7/inplace/place/repository/PlaceRepositoryTest.java
Labels: ✨ Feature

#10 [기능] 형식에 맞게 비디오 정보를 반환하는 기능
  src/main/java/team7/inplace/video/DTO/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/VideoData.java
  src/main/java/team7/inplace/video/DTO/VideoResponse.java
  src/main/java/team7/inplace/video/controller/VideoController.java
  src/main/java/team7/inplace/video/entity/Influencer.java
  src/main/java/team7/inplace/video/entity/Place.java
  src/main/java/team7/inplace/video/entity/Video.java
  src/main/java/team7/inplace/video/repository/InfluencerRepository.java
  src/main/java/team7/inplace/video/repository/VideoRepository.java
  src/main/java/team7/inplace/video/service/VideoService.java
Labels: ✨ Feature

#12 [기능] CI/CD 파이프라인을 구현했어요
  .github/workflows/gradle.yml
Labels: ✨ Feature

#13 [1주차 Weekly]
  .github/workflows/gradle.yml
  README.md
  src/main/java/team7/inplace/place/controller/PlaceController.java
  src/main/java/team7/inplace/place/domain/Category.java
  src/main/java/team7/inplace/place/domain/CategoryListDTO.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/place/repository/PlaceRepository.java
  src/main/java/team7/inplace/place/service/PlaceService.java
  src/main/java/team7/inplace/place/service/PlaceServiceImpl.java
  src/main/java/team7/inplace/video/DTO/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/VideoData.java
  src/main/java/team7/inplace/video/DTO/VideoResponse.java
  src/main/java/team7/inplace/video/controller/VideoController.java
  src/main/java/team7/inplace/video/entity/Influencer.java
  src/main/java/team7/inplace/video/entity/Place.java
  src/main/java/team7/inplace/video/entity/Video.java
  src/main/java/team7/inplace/video/repository/InfluencerRepository.java
  src/main/java/team7/inplace/video/repository/VideoRepository.java
  src/main/java/team7/inplace/video/service/VideoService.java
  src/test/java/team7/inplace/place/controller/PlaceControllerTest.java
  src/test/java/team7/inplace/place/repository/PlaceRepositoryTest.java
Labels: ✨ Feature

#14 [1주차 Develop -> Master]
  .github/workflows/gradle.yml
  README.md
  src/main/java/team7/inplace/place/controller/PlaceController.java
  src/main/java/team7/inplace/place/domain/Category.java
  src/main/java/team7/inplace/place/domain/CategoryListDTO.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/place/repository/PlaceRepository.java
  src/main/java/team7/inplace/place/service/PlaceService.java
  src/main/java/team7/inplace/place/service/PlaceServiceImpl.java
  src/main/java/team7/inplace/video/DTO/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/VideoData.java
  src/main/java/team7/inplace/video/DTO/VideoResponse.java
  src/main/java/team7/inplace/video/controller/VideoController.java
  src/main/java/team7/inplace/video/entity/Influencer.java
  src/main/java/team7/inplace/video/entity/Place.java
  src/main/java/team7/inplace/video/entity/Video.java
  src/main/java/team7/inplace/video/repository/InfluencerRepository.java
  src/main/java/team7/inplace/video/repository/VideoRepository.java
  src/main/java/team7/inplace/video/service/VideoService.java
  src/test/java/team7/inplace/place/controller/PlaceControllerTest.java
  src/test/java/team7/inplace/place/repository/PlaceRepositoryTest.java
Labels: ✨ Feature

#15 [Weekly1] 코드 리뷰 요청드립니다.
  .github/workflows/gradle.yml
  README.md
  src/main/java/team7/inplace/place/controller/PlaceController.java
  src/main/java/team7/inplace/place/domain/Category.java
  src/main/java/team7/inplace/place/domain/CategoryListDTO.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/place/repository/PlaceRepository.java
  src/main/java/team7/inplace/place/service/PlaceService.java
  src/main/java/team7/inplace/place/service/PlaceServiceImpl.java
  src/main/java/team7/inplace/video/DTO/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/VideoData.java
  src/main/java/team7/inplace/video/DTO/VideoResponse.java
  src/main/java/team7/inplace/video/controller/VideoController.java
  src/main/java/team7/inplace/video/entity/Influencer.java
  src/main/java/team7/inplace/video/entity/Place.java
  src/main/java/team7/inplace/video/entity/Video.java
  src/main/java/team7/inplace/video/repository/InfluencerRepository.java
  src/main/java/team7/inplace/video/repository/VideoRepository.java
  src/main/java/team7/inplace/video/service/VideoService.java
  src/test/java/team7/inplace/place/controller/PlaceControllerTest.java
  src/test/java/team7/inplace/place/repository/PlaceRepositoryTest.java
Labels: ✨ Feature

#16 [Feat] #5 videoAlias 정보를 랜덤하게 매핑해주는 기능을 구현했어요!
  src/main/java/team7/inplace/influencer/entity/Influencer.java
  src/main/java/team7/inplace/influencer/repository/InfluencerRepository.java
  src/main/java/team7/inplace/place/dto/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/PlaceForVideo.java
  src/main/java/team7/inplace/video/DTO/VideoData.java
  src/main/java/team7/inplace/video/DTO/VideoResponse.java
  src/main/java/team7/inplace/video/application/AliasUtil.java
  src/main/java/team7/inplace/video/application/Template.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/application/dto/VideoInfo.java
  src/main/java/team7/inplace/video/controller/VideoController.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/java/team7/inplace/video/entity/Influencer.java
  src/main/java/team7/inplace/video/entity/Place.java
  src/main/java/team7/inplace/video/entity/Video.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/dto/VideoResponse.java
  src/main/java/team7/inplace/video/service/VideoService.java
  src/test/java/team7/inplace/VideoTest/domain/VideoTest.java
  src/test/java/team7/inplace/VideoTest/repository/VideoRepositoryTest.java
  src/test/java/team7/inplace/VideoTest/service/VideoServiceTest.java
Labels: ✨ Feature, 📬 API

#17 [feat] #2 Oauth2 로그인 authentication을 구현하였습니다.
  .gitignore
  .gitmodules
  build.gradle
  src/main/java/team7/inplace/InplaceApplication.java
  src/main/java/team7/inplace/security/application/CustomOAuth2UserService.java
  src/main/java/team7/inplace/security/application/dto/CustomOAuth2User.java
  src/main/java/team7/inplace/security/application/dto/KakaoOAuthResponse.java
  src/main/java/team7/inplace/security/config/JwtProperties.java
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/config/SecurityServiceConfig.java
  src/main/java/team7/inplace/security/config/SecurityUtilConfig.java
  src/main/java/team7/inplace/security/domain/User.java
  src/main/java/team7/inplace/security/domain/UserType.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/security/persistence/UserRepository.java
  src/main/java/team7/inplace/security/util/JwtUtil.java
  src/main/java/team7/inplace/video/service/VideoService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#24 [Weekly] 2주차 Weekly 수정 PR
  .gitignore
  src/main/resources/application-security.yaml
  src/main/resources/application-youtube.yaml
  src/main/resources/application.yaml
  src/main/resources/application.yml
Labels: ⚙ Setting
