Repository kakao-tech-campus-2nd-step3/Team7_BE, pull requests merged in 2024-10, with the labels that each got.

#21 [Feat] #6 로그인 없이 공통으로 조회할 수 있는 다양한 조건의 비디오 조회 기능을 구현했어요!
  build.gradle
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/dto/VideoSearchParams.java
  src/main/resources/application.yaml
  src/test/java/team7/inplace/video/domain/VideoTest.java
  src/test/java/team7/inplace/video/repository/VideoRepositoryTest.java
  src/test/java/team7/inplace/video/service/VideoServiceTest.java
Labels: ✨ Feature, 📬 API

#32 [Feat] #2 authorization을 구현했어요.
  src/main/java/team7/inplace/global/exception/InplaceException.java
  src/main/java/team7/inplace/global/exception/code/AuthorizationErrorCode.java
  src/main/java/team7/inplace/global/exception/code/ErrorCode.java
  src/main/java/team7/inplace/security/application/CustomOAuth2UserService.java
  src/main/java/team7/inplace/security/application/dto/CustomOAuth2User.java
  src/main/java/team7/inplace/security/application/dto/KakaoOAuthResponse.java
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/config/SecurityFilterConfig.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/config/SecurityServiceConfig.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/security/util/AuthorizationUtil.java
  src/main/java/team7/inplace/security/util/JwtUtil.java
  src/main/java/team7/inplace/user/application/UserService.java
  src/main/java/team7/inplace/user/application/dto/UserCommand.java
  src/main/java/team7/inplace/user/domain/User.java
  src/main/java/team7/inplace/user/domain/UserType.java
  src/main/java/team7/inplace/user/persistence/UserRepository.java
  src/test/java/team7/inplace/security/util/JwtUtilTest.java
Labels: ✨ Feature

#30 [Refactor] #29 Swagger 코드 스타일과 패키지 네이밍 컨벤션을 맞춰 보아요
  src/main/java/team7/inplace/video/application/AliasUtil.java
  src/main/java/team7/inplace/video/application/Template.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: 🔨 Refactor

#31 [Feat] #8 CI/CD 관련 수정했어요
  .github/workflows/gradle.yml
  Dockerfile
  src/main/java/team7/inplace/cicd/TestController.java
Labels: ✨ Feature

#33 [Feat]#9 유튜브에서 장소 정보를 크롤링해요
  .gitignore
  src/main/java/team7/inplace/crawling/application/YoutubeCrawlingService.java
  src/main/java/team7/inplace/crawling/client/KakaoMapClient.java
  src/main/java/team7/inplace/crawling/client/YoutubeClient.java
  src/main/java/team7/inplace/crawling/client/dto/RawPlace.java
  src/main/java/team7/inplace/crawling/client/dto/RawVideoInfo.java
  src/main/java/team7/inplace/crawling/domain/ChannelType.java
  src/main/java/team7/inplace/crawling/domain/YoutubeChannel.java
  src/main/java/team7/inplace/crawling/persistence/YoutubeChannelRepository.java
  src/main/java/team7/inplace/global/kakao/config/KakaoApiProperties.java
  src/main/java/team7/inplace/global/rest/RestTemplateConfig.java
  src/main/java/team7/inplace/place/config/DataLoader.java
  src/main/java/team7/inplace/place/domain/Address.java
  src/main/java/team7/inplace/place/domain/Coordinate.java
  src/main/java/team7/inplace/place/domain/Menu.java
  src/main/java/team7/inplace/place/domain/OffDay.java
  src/main/java/team7/inplace/place/domain/OpenTime.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/place/domain/PlaceOpenTime.java
  src/main/resources/application-db.yaml
  src/main/resources/application-kakao.yaml
  src/main/resources/application.yaml
  src/test/java/team7/inplace/InplaceApplicationTests.java
  src/test/java/team7/inplace/crawling/client/KakaoMapClientTest.java
  src/test/java/team7/inplace/crawling/client/YoutubeClientTest.java
  src/test/java/team7/inplace/place/application/PlaceServiceTest.java
  src/test/java/team7/inplace/place/persistence/PlaceRepositoryTest.java
  src/test/java/team7/inplace/place/presentation/PlaceControllerTest.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/domain/VideoTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: ✨ Feature

#38 [Refactor] #37 비디오에 대한 5주차 코드 리뷰 내용을 반영해보아요
  src/main/java/team7/inplace/global/exception/code/VideoErrorCode.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
  src/test/java/team7/inplace/video/application/VideoServiceTest.java
  src/test/java/team7/inplace/video/persistence/VideoRepositoryTest.java
Labels: 🔨 Refactor

#42 [fix] #2 Anonymous 유저로 접근 시, 토큰이 없다는 에러 발생 문제 해결
  build.gradle
  src/main/java/team7/inplace/security/application/CustomOAuth2UserService.java
  src/main/java/team7/inplace/security/application/dto/CustomOAuth2User.java
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/config/SecurityFilterConfig.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/config/SecurityServiceConfig.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/security/util/AuthorizationUtil.java
  src/main/java/team7/inplace/security/util/JwtUtil.java
  src/main/java/team7/inplace/user/application/dto/UserCommand.java
  src/main/java/team7/inplace/user/domain/Role.java
  src/main/java/team7/inplace/user/domain/User.java
  src/main/resources/application-db.yaml
  src/main/resources/application.yaml
  src/test/java/team7/inplace/security/util/AuthorizationUtilTest.java
  src/test/java/team7/inplace/security/util/JwtUtilTest.java
Labels: ✨ Feature, 🐞 BugFix

#43 [Feat] #20 인플루언서 추가 수정 삭제 기능 + CI/CD 환경변수 추가했어요
  .github/workflows/gradle.yml
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/influencer/application/dto/InfluencerCommand.java
  src/main/java/team7/inplace/influencer/config/InfluencerDataLoader.java
  src/main/java/team7/inplace/influencer/domain/Influencer.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerController.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerControllerApiSpec.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerRequest.java
  src/main/resources/application-db.yaml
  src/test/java/team7/inplace/influencer/InfluencerRepositoryTest.java
  src/test/java/team7/inplace/influencer/InfluencerServiceTest.java
Labels: ✨ Feature

#51 [Fix] 크롤링 시 발생할 수 있는 문제를 수정합니다.
  src/main/java/team7/inplace/crawling/application/AddressUtil.java
  src/main/java/team7/inplace/crawling/application/YoutubeCrawlingService.java
  src/main/java/team7/inplace/crawling/application/dto/CrawlingInfo.java
  src/main/java/team7/inplace/crawling/client/KakaoMapClient.java
  src/main/java/team7/inplace/crawling/domain/YoutubeChannel.java
  src/main/java/team7/inplace/place/application/command/PlacesCommand.java
  src/main/java/team7/inplace/place/application/dto/PlaceDetailInfo.java
  src/main/java/team7/inplace/place/domain/Address.java
  src/main/java/team7/inplace/place/domain/Category.java
  src/main/java/team7/inplace/place/domain/Menu.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/video/application/AliasUtil.java
  src/main/java/team7/inplace/video/application/Template.java
  src/main/java/team7/inplace/video/domain/Video.java
  src/test/java/team7/inplace/crawling/application/AddressUtilTest.java
Labels: 🐞 BugFix

#52 [refactor] #7 MenuInfos-menuList 제거
  src/main/java/team7/inplace/global/queryDsl/QueryDslConfig.java
  src/main/java/team7/inplace/place/application/dto/PlaceDetailInfo.java
  src/main/java/team7/inplace/place/persistence/PlaceCustomRepository.java
  src/main/java/team7/inplace/place/persistence/PlaceCustomRepositoryImpl.java
Labels: 🔨 Refactor

#60 [Feat]#8 weekly에서 배포되도록 변경했어요
  .github/workflows/gradle.yml
Labels: 🌏 Deploy

#62 [Refactor] #49 통합 과정에서 발생하는 사항을 리펙터링 했어요
  src/main/java/team7/inplace/video/application/VideoFacade.java
  src/main/java/team7/inplace/video/application/VideoService.java
Labels: 🐞 BugFix, 🔨 Refactor

#61 [fix] oauth2login 실패 시, 무한 리다이렉트 해결
  src/main/generated/team7/inplace/crawling/domain/QYoutubeChannel.java
  src/main/generated/team7/inplace/favoriteInfluencer/domain/QFavoriteInfluencer.java
  src/main/generated/team7/inplace/influencer/domain/QInfluencer.java
  src/main/generated/team7/inplace/place/domain/QAddress.java
  src/main/generated/team7/inplace/place/domain/QCoordinate.java
  src/main/generated/team7/inplace/place/domain/QMenu.java
  src/main/generated/team7/inplace/place/domain/QOffDay.java
  src/main/generated/team7/inplace/place/domain/QOpenTime.java
  src/main/generated/team7/inplace/place/domain/QPlace.java
  src/main/generated/team7/inplace/user/domain/QUser.java
  src/main/generated/team7/inplace/video/domain/QVideo.java
  src/main/java/team7/inplace/security/application/CustomOAuth2UserService.java
  src/main/java/team7/inplace/security/application/dto/CustomOAuth2User.java
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/config/SecurityFilterConfig.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/config/SecurityUtilConfig.java
  src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
  src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
  src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
  src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
  src/main/java/team7/inplace/token/presentation/RefreshTokenControllerApiSpec.java
  src/main/java/team7/inplace/user/application/UserService.java
Labels: 🐞 BugFix

#64 [Fix] #44 cors Error를 해결하였습니다.
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#65 [fix] #44 cors error 수정 2
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#66 [fix] #44 cors error 수정3
  src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: 🐞 BugFix

#67 [feat] swagger permitAll로 설정
  src/main/java/team7/inplace/security/config/SecurityConfig.java
Labels: 🐞 BugFix

#69 [fix] #68 videos/cool API 호출에 대한 오류를 해결해요
  src/main/java/team7/inplace/video/presentation/VideoController.java
Labels: 🐞 BugFix

#71 [feat] Place에 menuboardImgUrls 추가 했어요!
  src/main/java/team7/inplace/crawling/application/YoutubeCrawlingService.java
  src/main/java/team7/inplace/crawling/persistence/YoutubeChannelRepository.java
  src/main/java/team7/inplace/global/exception/code/ChannelErrorCode.java
  src/main/java/team7/inplace/place/application/command/PlacesCommand.java
  src/main/java/team7/inplace/place/domain/Place.java
  src/main/java/team7/inplace/video/application/VideoFacade.java
Labels: ✨ Feature

#76 [feat] Url 반환 시 youtube url 반환하도록 변경
  src/main/java/team7/inplace/video/domain/Video.java
Labels: ✨ Feature

#77 [Feat] #50 login page 없애버리기
  src/main/java/team7/inplace/security/config/SecurityConfig.java
  src/main/java/team7/inplace/security/config/SecurityEntryPointConfig.java
  src/main/java/team7/inplace/security/config/SecurityHandlerConfig.java
  src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
  src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
Labels: ✨ Feature

#72 [Feat] #20 인플루언서 좋아요와 반영하여 반환하도록 했어요
  src/main/java/team7/inplace/favoriteInfluencer/domain/FavoriteInfluencer.java
  src/main/java/team7/inplace/favoriteInfluencer/persistent/FavoriteInfluencerRepository.java
  src/main/java/team7/inplace/influencer/application/InfluencerService.java
  src/main/java/team7/inplace/influencer/application/dto/InfluencerInfo.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerController.java
  src/main/java/team7/inplace/influencer/presentation/InfluencerControllerApiSpec.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerLikeRequest.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerRequest.java
  src/main/java/team7/inplace/influencer/presentation/dto/InfluencerRequestParam.java
  src/test/java/team7/inplace/influencer/InfluencerRepositoryTest.java
  src/test/java/team7/inplace/influencer/InfluencerServiceTest.java
Labels: ✨ Feature

#78 [fix] 값이 없을 경우 default 저장값을 변경했어요
  src/main/java/team7/inplace/place/application/command/PlacesCommand.java
Labels: 🔨 Refactor

#81 [Feat] #80 관리자 페이지 프로토 타입을 만들었어요
  build.gradle
  src/main/java/team7/inplace/admin/adminPageController.java
  src/main/java/team7/inplace/video/application/VideoService.java
  src/main/java/team7/inplace/video/persistence/VideoRepository.java
  src/main/java/team7/inplace/video/presentation/VideoController.java
  src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
  src/main/java/team7/inplace/video/presentation/dto/VideoResponse.java
  src/main/resources/static/index.html
  src/main/resources/static/index_style.css
  src/main/resources/templates/admin.html
Labels: ✨ Feature
